language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2
gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_head.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
bundler_args: --without local_development
